package com.sys.api.modules.envapi.beans;

import java.io.Serializable;

public class Accounts implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.USER
     *
     * @mbg.generated
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.HOST
     *
     * @mbg.generated
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.CURRENT_CONNECTIONS
     *
     * @mbg.generated
     */
    private Long currentConnections;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.TOTAL_CONNECTIONS
     *
     * @mbg.generated
     */
    private Long totalConnections;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accounts
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.USER
     *
     * @return the value of accounts.USER
     *
     * @mbg.generated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.USER
     *
     * @param user the value for accounts.USER
     *
     * @mbg.generated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.HOST
     *
     * @return the value of accounts.HOST
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.HOST
     *
     * @param host the value for accounts.HOST
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.CURRENT_CONNECTIONS
     *
     * @return the value of accounts.CURRENT_CONNECTIONS
     *
     * @mbg.generated
     */
    public Long getCurrentConnections() {
        return currentConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.CURRENT_CONNECTIONS
     *
     * @param currentConnections the value for accounts.CURRENT_CONNECTIONS
     *
     * @mbg.generated
     */
    public void setCurrentConnections(Long currentConnections) {
        this.currentConnections = currentConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.TOTAL_CONNECTIONS
     *
     * @return the value of accounts.TOTAL_CONNECTIONS
     *
     * @mbg.generated
     */
    public Long getTotalConnections() {
        return totalConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.TOTAL_CONNECTIONS
     *
     * @param totalConnections the value for accounts.TOTAL_CONNECTIONS
     *
     * @mbg.generated
     */
    public void setTotalConnections(Long totalConnections) {
        this.totalConnections = totalConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", user=").append(user);
        sb.append(", host=").append(host);
        sb.append(", currentConnections=").append(currentConnections);
        sb.append(", totalConnections=").append(totalConnections);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}