package com.sys.api.modules.envapi.dao;

import com.sys.api.modules.envapi.beans.Artcomment;
import java.util.List;

public interface ArtcommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcomment
     *
     * @mbg.generated
     */
    int insert(Artcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcomment
     *
     * @mbg.generated
     */
    List<Artcomment> selectAll();
}