package com.sys.api.modules.envapi.dao;

import com.sys.api.modules.envapi.beans.Euser;
import java.util.List;

public interface EuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated
     */
    int insert(Euser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euser
     *
     * @mbg.generated
     */
    List<Euser> selectAll();
}